"use client";

import Link from "next/link";
import {useEffect,useMemo,useRef,useState} from "react";
import {applications,jobs,statusCopy,type Job} from "../lib/fixtures";
import {Brand} from "./Brand";

export type ProductView="jobs"|"applications"|"saved"|"notifications"|"profile"|"universal";
const nav=[
  {id:"jobs",href:"/app/jobs",icon:"⌁",label:"Empleos"},
  {id:"applications",href:"/app/applications",icon:"↗",label:"Candidaturas"},
  {id:"saved",href:"/app/saved",icon:"♡",label:"Guardados"},
  {id:"notifications",href:"/app/notifications",icon:"◌",label:"Notificaciones"},
  {id:"profile",href:"/app/profile",icon:"◎",label:"Perfil"},
];

const capability={automatic:{label:"Automática verificada",detail:"Landeo puede preparar y enviar esta candidatura por un canal autorizado.",icon:"✓"},assisted:{label:"Candidatura asistida",detail:"Preparamos los campos y te avisamos si falta algo.",icon:"↗"},external:{label:"Finalización externa",detail:"Terminarás la candidatura en la web oficial.",icon:"↗"}};

function initials(value:string){return value.split(" ").map(x=>x[0]).slice(0,2).join("")}
function money(job:Job){if(!job.salaryMin||!job.salaryMax)return "Salario no publicado";const n=(v:number)=>new Intl.NumberFormat("es-ES",{style:"currency",currency:job.salaryCurrency,maximumFractionDigits:0}).format(v);return `${n(job.salaryMin)}–${n(job.salaryMax)}`}

export default function ProductApp({view}:{view:ProductView}){
  const [lang,setLang]=useState("ES");
  const [mobileNav,setMobileNav]=useState(false);
  return <div className="app-frame">
    <aside className={`app-sidebar ${mobileNav?"open":""}`}>
      <div className="sidebar-brand"><Brand/><button aria-label="Cerrar menú" onClick={()=>setMobileNav(false)}>×</button></div>
      <div className="profile-mini"><span>AM</span><div><strong>Alberto</strong><small>Perfil al 75%</small></div><b>Pro</b></div>
      <nav aria-label="Navegación de la aplicación">{nav.map(item=><Link key={item.id} href={item.href} className={view===item.id?"active":""}><i>{item.icon}</i>{item.label}{item.id==="notifications"&&<em>3</em>}</Link>)}</nav>
      <div className="profile-progress"><div><strong>Tu perfil universal</strong><span>75%</span></div><progress value="75" max="100">75%</progress><p>Completa 3 bloques para mejorar tus candidaturas.</p><Link href="/app/profile/universal">Completar perfil →</Link></div>
      <div className="sidebar-foot"><button className="lang-toggle" onClick={()=>setLang(lang==="ES"?"EN":"ES")}><span>◉</span>{lang} <b>⌄</b></button><span className="secure-note">Tus datos están protegidos</span></div>
    </aside>
    <div className="app-main"><header className="app-mobile-header"><button aria-label="Abrir menú" onClick={()=>setMobileNav(true)}>☰</button><Brand compact/><span className="avatar">AM</span></header>{renderView(view)}</div>
  </div>
}

function renderView(view:ProductView){
  if(view==="jobs")return <JobsView/>;
  if(view==="applications")return <ApplicationsView/>;
  if(view==="saved")return <SavedView/>;
  if(view==="notifications")return <NotificationsView/>;
  if(view==="universal")return <UniversalProfile/>;
  return <ProfileView/>;
}

function JobsView(){
  const [index,setIndex]=useState(0);const [saved,setSaved]=useState<string[]>([]);const [passed,setPassed]=useState<string[]>([]);const [query,setQuery]=useState("");const [mode,setMode]=useState("all");const [workMode,setWorkMode]=useState("all");const [paywall,setPaywall]=useState(false);const [notice,setNotice]=useState("");const dragStart=useRef<number|null>(null);
  const filtered=useMemo(()=>jobs.filter(j=>!passed.includes(j.id)&&(mode==="all"||j.applyCapability===mode)&&(workMode==="all"||j.workMode===workMode)&&`${j.title} ${j.company}`.toLowerCase().includes(query.toLowerCase())),[passed,mode,workMode,query]);
  const job=filtered[index%Math.max(filtered.length,1)];
  const pass=()=>{if(!job)return;setPassed(x=>[...x,job.id]);setIndex(0);setNotice("Oferta descartada. Puedes verla después en tu historial.")};
  const save=()=>{if(!job)return;const next=saved.includes(job.id)?saved.filter(x=>x!==job.id):[...saved,job.id];setSaved(next);localStorage.setItem("landeo:saved",JSON.stringify(next));setNotice(next.includes(job.id)?"Oferta guardada":"Oferta eliminada de guardados")};
  const apply=()=>{if(!job)return;setPaywall(true)};
  useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if((e.target as HTMLElement).matches("input,select,textarea"))return;if(e.key==="ArrowLeft")pass();if(e.key==="ArrowRight"||e.key==="Enter")apply();if(e.key.toLowerCase()==="s")save()};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)});
  return <>
    <header className="view-header"><div><span className="overline">DESCUBRE</span><h1>Empleos para ti</h1><p>Ordenados según tu perfil y tus preferencias.</p></div><div className="header-actions"><button aria-label="Abrir notificaciones">◌<i>3</i></button><span className="avatar">AM</span></div></header>
    <div className="jobs-layout">
      <aside className="filters-panel"><div className="filter-title"><strong>Filtros</strong><button onClick={()=>{setMode("all");setWorkMode("all");setQuery("")}}>Limpiar</button></div><label className="search-field"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cargo o empresa"/></label><label>Mercado<select defaultValue="ES"><option value="ES">España</option><option value="US">Estados Unidos</option><option value="GB">Reino Unido</option></select></label><fieldset><legend>Modalidad</legend>{[["all","Todas"],["remote","Remoto"],["hybrid","Híbrido"],["onsite","Presencial"]].map(x=><label key={x[0]} className="radio-row"><input type="radio" checked={workMode===x[0]} onChange={()=>setWorkMode(x[0])}/><span>{x[1]}</span></label>)}</fieldset><fieldset><legend>Tipo de candidatura</legend>{[["all","Todas"],["automatic","Automática"],["assisted","Asistida"],["external","Externa"]].map(x=><label key={x[0]} className="radio-row"><input type="radio" checked={mode===x[0]} onChange={()=>setMode(x[0])}/><span>{x[1]}</span></label>)}</fieldset><label className="check-row"><input type="checkbox"/><span>Solo con salario</span></label><div className="filter-note"><b>i</b><p><strong>Sobre la coincidencia</strong>Es una relevancia calculada con tus habilidades, modalidad y ubicación. No predice una contratación.</p></div></aside>
      <section className="deck-panel">
        <div className="deck-count"><span>{filtered.length?`${index+1} de ${filtered.length}`:"0 ofertas"}</span><div>{filtered.map((_,i)=><i key={i} className={i===index?"active":""}/>)}</div></div>
        {job?<div className="feed-card" role="button" tabIndex={0} aria-label={`Oferta de ${job.title} en ${job.company}. Desliza o usa las flechas.`} onKeyDown={e=>{if(e.key==="ArrowLeft")pass();if(e.key==="ArrowRight"||e.key==="Enter")apply()}} onPointerDown={e=>dragStart.current=e.clientX} onPointerUp={e=>{if(dragStart.current===null)return;const d=e.clientX-dragStart.current;if(d>80)apply();if(d< -80)pass();dragStart.current=null}}>
          <div className="feed-top"><span className="company-initials">{initials(job.company)}</span><div><strong>{job.company}</strong><small>{job.industry}</small></div><button className={saved.includes(job.id)?"is-saved":""} aria-label={saved.includes(job.id)?"Quitar de guardados":"Guardar oferta"} onClick={save}>{saved.includes(job.id)?"♥":"♡"}</button></div>
          <span className="fresh-badge">NUEVA</span><h2>{job.title}</h2><p>{job.summary}</p><div className="job-meta"><span>⌖ {job.location}</span><span>◫ {job.workMode==="remote"?"Remoto":job.workMode==="hybrid"?"Híbrido":"Presencial"}</span><span>◷ Hace 2 días</span></div><div className="salary-block"><span>€</span><div><small>Salario estimado</small><strong>{money(job)}</strong></div></div><div className="skill-row">{job.skills.map(skill=><span key={skill}>{skill}</span>)}</div><div className={`capability ${job.applyCapability}`}><b>{capability[job.applyCapability].icon}</b><div><strong>{capability[job.applyCapability].label}</strong><small>{capability[job.applyCapability].detail}</small></div></div>
        </div>:<div className="empty-state"><span>✓</span><h2>Estás al día</h2><p>Prueba a limpiar los filtros o vuelve más tarde para ver nuevas ofertas.</p></div>}
        {notice&&<div className="toast" role="status">{notice}<button onClick={()=>setNotice("")}>×</button></div>}
        <div className="deck-actions"><button className="action-pass" onClick={pass}><b>×</b><span>Pasar<small>←</small></span></button><button className="action-save" onClick={save}><b>♡</b><span>Guardar<small>S</small></span></button><button className="action-apply" onClick={apply}><b>→</b><span>Postularme<small>ENTER</small></span></button></div>
      </section>
      {job&&<aside className="detail-panel"><div className="detail-match"><div><strong>{job.match}%</strong><span>coincidencia</span></div><small>Alta relevancia</small></div><div className="match-reasons"><strong>Por qué encaja contigo</strong><p><i>✓</i>Coincide con 3 de tus habilidades</p><p><i>✓</i>Modalidad híbrida preferida</p><p><i>✓</i>Dentro de tu rango salarial</p></div><hr/><h3>Sobre el puesto</h3><p>{job.description}</p><h3>Lo que buscan</h3><ul>{job.skills.map(s=><li key={s}>{s}</li>)}<li>Comunicación y trabajo en equipo</li></ul><div className="detail-bottom"><Link href={`/app/jobs/${job.id}`}>Ver detalles completos →</Link><small>Fuente: portal oficial · Verificada hoy</small></div></aside>}
    </div>
    {paywall&&<div className="modal-backdrop"><button className="modal-scrim" aria-label="Cerrar ventana de Landeo Pro" onClick={()=>setPaywall(false)}/><section className="paywall-modal" role="dialog" aria-modal="true" aria-labelledby="paywall-title"><button className="modal-close" onClick={()=>setPaywall(false)} aria-label="Cerrar">×</button><span className="pro-gem">✦</span><p className="overline">LANDEO PRO</p><h2 id="paywall-title">Tu perfil está listo para dar el siguiente paso.</h2><p>Postularse requiere Pro. El servidor comprobará tu acceso y tus consentimientos antes de iniciar nada.</p><ul><li>✓ Candidaturas con tu perfil universal</li><li>✓ Seguimiento con estados verificables</li><li>✓ Cancela cuando quieras</li></ul><Link className="button button-primary" href="/pricing">Ver planes Pro →</Link><button className="text-button" onClick={()=>setPaywall(false)}>Seguir explorando gratis</button></section></div>}
  </>;
}

function ApplicationsView(){const [selected,setSelected]=useState(applications[0]);return <><header className="view-header"><div><span className="overline">SEGUIMIENTO</span><h1>Mis candidaturas</h1><p>El estado real de cada proceso, en un solo lugar.</p></div><div className="header-actions"><span className="avatar">AM</span></div></header><div className="applications-layout"><section className="applications-list"><div className="status-tabs"><button className="active">Todas <b>3</b></button><button>En curso <b>2</b></button><button>Enviadas <b>1</b></button></div>{applications.map(app=><button key={app.id} className={`application-row ${selected.id===app.id?"selected":""}`} onClick={()=>setSelected(app)}><span className="company-initials">{initials(app.job.company)}</span><div className="application-title"><strong>{app.job.title}</strong><span>{app.job.company} · {app.job.location}</span><small>{app.date}</small></div><span className={`status-badge ${app.status}`}>{statusCopy[app.status].label}</span></button>)}</section><aside className="application-detail"><span className={`status-badge ${selected.status}`}>{statusCopy[selected.status].label}</span><h2>{selected.job.title}</h2><p>{selected.job.company} · {selected.job.location}</p><div className="status-explain"><strong>{statusCopy[selected.status].label}</strong><span>{statusCopy[selected.status].description}</span></div><h3>Cronología</h3><ol className="timeline">{selected.events.map((e,i)=><li key={e} className={i===selected.events.length-1?"current":"done"}><i/ ><div><strong>{e}</strong><small>{i===0?selected.date:i===selected.events.length-1?"Estado actual":"Hace 18 min"}</small></div></li>)}</ol>{selected.status==="action_required"&&<button className="button button-primary">Completar en la web oficial →</button>}<div className="application-trust"><b>i</b><p>Landeo solo marca una candidatura como enviada cuando el canal confirma la entrega.</p></div></aside></div></>}

function SavedView(){const [ids,setIds]=useState<string[]>(jobs.slice(0,3).map(j=>j.id));return <><header className="view-header"><div><span className="overline">TU LISTA</span><h1>Empleos guardados</h1><p>Vuelve cuando quieras y decide con calma.</p></div></header><div className="content-narrow"><div className="saved-grid">{jobs.filter(j=>ids.includes(j.id)).map(j=><article className="saved-card" key={j.id}><div><span className="company-initials">{initials(j.company)}</span><button onClick={()=>setIds(x=>x.filter(id=>id!==j.id))} aria-label="Quitar de guardados">♥</button></div><small>{j.company}</small><h2>{j.title}</h2><p>⌖ {j.location} · {j.workMode==="remote"?"Remoto":"Híbrido"}</p><div><span className={`mini-cap ${j.applyCapability}`}>{capability[j.applyCapability].label}</span><strong>{j.match}%</strong></div><Link href={`/app/jobs/${j.id}`}>Ver oferta →</Link></article>)}</div></div></>}

function NotificationsView(){const items=[{title:"Acción necesaria",text:"Clarity AI necesita una respuesta adicional para continuar.",time:"Hace 12 min",kind:"warning"},{title:"Candidatura en proceso",text:"Estamos preparando tu candidatura para Typeform.",time:"Hace 1 h",kind:"info"},{title:"Entrega confirmada",text:"La candidatura para Data Analyst se ha enviado correctamente.",time:"Ayer",kind:"success"}];return <><header className="view-header"><div><span className="overline">ACTUALIZACIONES</span><h1>Notificaciones</h1><p>Eventos importantes de tus candidaturas.</p></div><button className="text-button">Marcar todo como leído</button></header><div className="content-narrow"><section className="notification-list">{items.map(item=><article key={item.title}><span className={item.kind}>{item.kind==="success"?"✓":item.kind==="warning"?"!":"i"}</span><div><strong>{item.title}</strong><p>{item.text}</p><small>{item.time}</small></div><i/></article>)}</section></div></>}

function ProfileView(){return <><header className="view-header"><div><span className="overline">TU CUENTA</span><h1>Perfil</h1><p>Gestiona tus datos, preferencias y acceso.</p></div></header><div className="profile-content"><section className="profile-hero"><span className="large-avatar">AM</span><div><h2>Alberto Menéndez</h2><p>Product Designer · Madrid, España</p><span className="pro-pill">✦ Landeo Pro</span></div><button>Editar perfil</button></section><div className="profile-dashboard"><Link href="/app/profile/universal" className="completion-card"><div className="ring"><strong>75%</strong></div><div><span className="overline">PERFIL UNIVERSAL</span><h2>Tu base para cada candidatura</h2><p>Te faltan idiomas, disponibilidad y una motivación general.</p><b>Completar perfil →</b></div></Link><section className="settings-card"><h3>Cuenta y preferencias</h3>{["Datos personales","Preferencias de empleo","Idioma y mercado","Gestionar suscripción","Privacidad y autorizaciones"].map(x=><button key={x}><span>{x}</span><b>›</b></button>)}</section><section className="settings-card danger-zone"><h3>Sesión y datos</h3><button><span>Cerrar sesión</span><b>›</b></button><button><span>Descargar mis datos</span><b>›</b></button><button className="danger"><span>Eliminar cuenta</span><b>›</b></button></section></div></div></>}

function UniversalProfile(){const blocks=["Identidad y contacto","CV","Enlaces profesionales","Salario","Disponibilidad","Autorización laboral y visado","Preferencias de modalidad","Idiomas","Experiencia","Motivación","Prácticas y convenio","Consentimientos"];const [done,setDone]=useState([0,1,2,3,5,6,8,11]);const pct=Math.round(done.length/blocks.length*100);return <><header className="view-header universal-head"><div><Link href="/app/profile">← Volver al perfil</Link><span className="overline">PERFIL UNIVERSAL</span><h1>Una vez. Para cada oportunidad.</h1><p>Esta información prepara tus candidaturas. Siempre podrás revisarla antes de compartirla.</p></div><div className="universal-progress"><strong>{pct}%</strong><span>completado</span><progress value={pct} max="100"/></div></header><div className="universal-layout"><nav className="block-nav">{blocks.map((b,i)=><button key={b} className={done.includes(i)?"done":""}><i>{done.includes(i)?"✓":i+1}</i><span>{b}</span></button>)}</nav><section className="profile-form"><span className="overline">01 · IDENTIDAD Y CONTACTO</span><h2>Cuéntanos quién eres</h2><p>Usaremos estos datos en tus candidaturas cuando tú lo autorices.</p><div className="form-grid"><label>Nombre<input aria-label="Nombre" defaultValue="Alberto"/></label><label>Apellidos<input aria-label="Apellidos" defaultValue="Menéndez"/></label><label>Email<input aria-label="Email" type="email" defaultValue="alberto@example.com"/></label><label>Teléfono<input aria-label="Teléfono" type="tel" placeholder="+34 600 000 000"/></label><label>Ciudad<input aria-label="Ciudad" defaultValue="Madrid"/></label><label>País<select aria-label="País" defaultValue="ES"><option value="ES">España</option><option value="US">Estados Unidos</option></select></label><label className="full">Título profesional<input aria-label="Título profesional" defaultValue="Product Designer"/></label></div><div className="consent-box"><label><input aria-label="Autorización de candidatura" type="checkbox" defaultChecked/><span><strong>Autorización de candidatura</strong><small>Autorizo a Landeo a preparar candidaturas únicamente cuando exprese mi intención.</small></span></label></div><div className="form-actions"><span>Los cambios se guardan de forma segura.</span><button className="button button-primary" onClick={()=>setDone(Array.from(new Set([...done,0])))}>Guardar y continuar →</button></div></section></div></>}
