import type { Job } from "./fixtures";

type DemoInput = Pick<
  Job,
  "id" | "company" | "title" | "location" | "market" | "workMode" | "industry"
> & {
  logo: string;
  summary: string;
  skills: string[];
  salaryMin: number;
  salaryMax: number;
};

function demoJob(input: DemoInput, index: number): Job {
  return {
    ...input,
    description: `${input.summary} Esta es una oferta ficticia creada exclusivamente para demostrar la experiencia de Landeo; no corresponde a una vacante real.`,
    salaryCurrency: input.market === "GB" ? "GBP" : "USD",
    contractType: "Full time",
    seniority:
      index % 3 === 0 ? "Senior" : index % 3 === 1 ? "Mid level" : "Lead",
    applyCapability: index % 4 === 0 ? "assisted" : "automatic",
    match: 96 - (index % 8),
    publishedAt: new Date(Date.UTC(2026, 8, 9 - (index % 5))).toISOString(),
    source: "DEMO",
    applyProvider: "simulation",
    applyMode: "demo",
    metadata: { demo: true, company_logo: input.logo },
  };
}

const demoInputs: DemoInput[] = [
  {
    id: "demo-google-ai-pm",
    company: "Google",
    title: "Product Manager, Generative AI",
    location: "Mountain View, CA",
    market: "US",
    workMode: "hybrid",
    industry: "Artificial Intelligence",
    logo: "/company-logos/google.webp",
    summary:
      "Define productos de IA usados por equipos de todo el mundo y coordina producto, diseño e ingeniería.",
    skills: ["Product strategy", "AI", "Analytics"],
    salaryMin: 180000,
    salaryMax: 245000,
  },
  {
    id: "demo-google-cloud",
    company: "Google",
    title: "Senior Software Engineer, Cloud",
    location: "New York, NY",
    market: "US",
    workMode: "hybrid",
    industry: "Cloud",
    logo: "/company-logos/google.webp",
    summary:
      "Construye servicios distribuidos fiables para una plataforma cloud de escala global.",
    skills: ["Go", "Distributed systems", "GCP"],
    salaryMin: 190000,
    salaryMax: 260000,
  },
  {
    id: "demo-apple-designer",
    company: "Apple",
    title: "Senior Product Designer",
    location: "Cupertino, CA",
    market: "US",
    workMode: "hybrid",
    industry: "Consumer Technology",
    logo: "/company-logos/apple.svg",
    summary:
      "Diseña experiencias sencillas y cuidadas para productos utilizados por millones de personas.",
    skills: ["Product design", "Prototyping", "Research"],
    salaryMin: 175000,
    salaryMax: 230000,
  },
  {
    id: "demo-apple-ml",
    company: "Apple",
    title: "Machine Learning Engineer",
    location: "Seattle, WA",
    market: "US",
    workMode: "hybrid",
    industry: "Machine Learning",
    logo: "/company-logos/apple.svg",
    summary:
      "Desarrolla modelos y sistemas de aprendizaje automático centrados en privacidad y rendimiento.",
    skills: ["Python", "PyTorch", "MLOps"],
    salaryMin: 185000,
    salaryMax: 250000,
  },
  {
    id: "demo-openai-research",
    company: "OpenAI",
    title: "Research Engineer",
    location: "San Francisco, CA",
    market: "US",
    workMode: "hybrid",
    industry: "AI Research",
    logo: "/company-logos/openai.png",
    summary:
      "Convierte avances de investigación en sistemas de inteligencia artificial robustos y útiles.",
    skills: ["Python", "Deep learning", "Evaluation"],
    salaryMin: 220000,
    salaryMax: 320000,
  },
  {
    id: "demo-openai-product",
    company: "OpenAI",
    title: "Product Operations Lead",
    location: "Remote — United States",
    market: "US",
    workMode: "remote",
    industry: "AI Products",
    logo: "/company-logos/openai.png",
    summary:
      "Crea procesos de lanzamiento y aprendizaje para productos de inteligencia artificial en rápido crecimiento.",
    skills: ["Operations", "Product", "Strategy"],
    salaryMin: 190000,
    salaryMax: 260000,
  },
  {
    id: "demo-anthropic-safety",
    company: "Anthropic",
    title: "AI Safety Researcher",
    location: "San Francisco, CA",
    market: "US",
    workMode: "hybrid",
    industry: "AI Safety",
    logo: "/company-logos/anthropic.webp",
    summary:
      "Investiga métodos para comprender, evaluar y mejorar la seguridad de modelos avanzados.",
    skills: ["Research", "LLMs", "Statistics"],
    salaryMin: 230000,
    salaryMax: 340000,
  },
  {
    id: "demo-anthropic-success",
    company: "Anthropic",
    title: "Enterprise Customer Success Lead",
    location: "Remote — Europe",
    market: "REMOTE",
    workMode: "remote",
    industry: "Enterprise AI",
    logo: "/company-logos/anthropic.webp",
    summary:
      "Ayuda a grandes organizaciones a implementar inteligencia artificial de manera efectiva y responsable.",
    skills: ["Enterprise", "AI", "Customer success"],
    salaryMin: 145000,
    salaryMax: 205000,
  },
  {
    id: "demo-tesla-data",
    company: "Tesla",
    title: "Senior Data Scientist",
    location: "Austin, TX",
    market: "US",
    workMode: "onsite",
    industry: "Mobility",
    logo: "/company-logos/tesla.png",
    summary:
      "Transforma datos industriales y de producto en decisiones que mejoran operaciones a gran escala.",
    skills: ["Python", "SQL", "Forecasting"],
    salaryMin: 155000,
    salaryMax: 215000,
  },
  {
    id: "demo-tesla-ux",
    company: "Tesla",
    title: "UX Engineer",
    location: "Palo Alto, CA",
    market: "US",
    workMode: "hybrid",
    industry: "Automotive Software",
    logo: "/company-logos/tesla.png",
    summary:
      "Diseña y construye interfaces de producto donde la interacción y el rendimiento son esenciales.",
    skills: ["React", "Interaction", "Prototyping"],
    salaryMin: 160000,
    salaryMax: 220000,
  },
  {
    id: "demo-spacex-backend",
    company: "SpaceX",
    title: "Backend Software Engineer",
    location: "Hawthorne, CA",
    market: "US",
    workMode: "onsite",
    industry: "Aerospace",
    logo: "/company-logos/spacex.png",
    summary:
      "Desarrolla sistemas internos que coordinan operaciones complejas y datos de ingeniería.",
    skills: ["Python", "PostgreSQL", "APIs"],
    salaryMin: 150000,
    salaryMax: 210000,
  },
  {
    id: "demo-spacex-product",
    company: "SpaceX",
    title: "Product Manager, Starlink",
    location: "Redmond, WA",
    market: "US",
    workMode: "hybrid",
    industry: "Connectivity",
    logo: "/company-logos/spacex.png",
    summary:
      "Lidera experiencias de conectividad que acercan internet de alta velocidad a nuevos mercados.",
    skills: ["Product", "Connectivity", "Growth"],
    salaryMin: 165000,
    salaryMax: 225000,
  },
  {
    id: "demo-spotify-growth",
    company: "Spotify",
    title: "Growth Product Manager",
    location: "New York, NY",
    market: "US",
    workMode: "hybrid",
    industry: "Audio Streaming",
    logo: "/company-logos/spotify.png",
    summary:
      "Diseña experimentos de crecimiento que ayudan a más personas a descubrir audio relevante.",
    skills: ["Growth", "Experimentation", "Analytics"],
    salaryMin: 155000,
    salaryMax: 215000,
  },
  {
    id: "demo-spotify-frontend",
    company: "Spotify",
    title: "Senior Frontend Engineer",
    location: "Remote — EMEA",
    market: "REMOTE",
    workMode: "remote",
    industry: "Consumer Software",
    logo: "/company-logos/spotify.png",
    summary:
      "Construye experiencias web rápidas y accesibles para usuarios y creadores de todo el mundo.",
    skills: ["React", "TypeScript", "Accessibility"],
    salaryMin: 135000,
    salaryMax: 190000,
  },
  {
    id: "demo-notion-design",
    company: "Notion",
    title: "Staff Product Designer",
    location: "San Francisco, CA",
    market: "US",
    workMode: "hybrid",
    industry: "Productivity",
    logo: "/company-logos/notion.webp",
    summary:
      "Define nuevas formas de trabajar combinando sistemas flexibles, IA y una experiencia excepcional.",
    skills: ["Systems design", "AI UX", "Research"],
    salaryMin: 190000,
    salaryMax: 255000,
  },
  {
    id: "demo-notion-engineer",
    company: "Notion",
    title: "Full Stack Engineer",
    location: "Remote — Worldwide",
    market: "REMOTE",
    workMode: "remote",
    industry: "Collaboration",
    logo: "/company-logos/notion.webp",
    summary:
      "Crea herramientas colaborativas desde la infraestructura hasta la experiencia final del usuario.",
    skills: ["TypeScript", "React", "Node.js"],
    salaryMin: 175000,
    salaryMax: 240000,
  },
  {
    id: "demo-hubspot-marketing",
    company: "HubSpot",
    title: "Senior Product Marketing Manager",
    location: "Remote — Europe",
    market: "REMOTE",
    workMode: "remote",
    industry: "SaaS",
    logo: "/company-logos/hubspot.png",
    summary:
      "Convierte conocimiento del cliente en posicionamiento, lanzamientos y crecimiento de producto.",
    skills: ["Positioning", "Go-to-market", "Research"],
    salaryMin: 130000,
    salaryMax: 180000,
  },
  {
    id: "demo-hubspot-platform",
    company: "HubSpot",
    title: "Platform Engineer",
    location: "London, UK",
    market: "GB",
    workMode: "hybrid",
    industry: "Developer Platform",
    logo: "/company-logos/hubspot.png",
    summary:
      "Mejora la plataforma que permite a equipos de producto lanzar software con rapidez y confianza.",
    skills: ["Kubernetes", "AWS", "Observability"],
    salaryMin: 110000,
    salaryMax: 155000,
  },
  {
    id: "demo-mckinsey-associate",
    company: "McKinsey & Company",
    title: "Digital Strategy Associate",
    location: "New York, NY",
    market: "US",
    workMode: "hybrid",
    industry: "Consulting",
    logo: "/company-logos/mckinsey.png",
    summary:
      "Ayuda a organizaciones líderes a convertir retos tecnológicos en estrategias de transformación.",
    skills: ["Strategy", "Technology", "Communication"],
    salaryMin: 170000,
    salaryMax: 220000,
  },
  {
    id: "demo-mckinsey-analytics",
    company: "McKinsey & Company",
    title: "Analytics Specialist",
    location: "Remote — Europe",
    market: "REMOTE",
    workMode: "remote",
    industry: "Analytics Consulting",
    logo: "/company-logos/mckinsey.png",
    summary:
      "Combina análisis avanzado y visión de negocio para resolver decisiones complejas de clientes.",
    skills: ["Analytics", "Python", "Consulting"],
    salaryMin: 125000,
    salaryMax: 175000,
  },
];

export const marketingDemoJobs = demoInputs.map(demoJob);
